<a href="https://colab.research.google.com/github/adtitovich/dsml-17/blob/main/m2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd

# загружаем датасет с ириcами
data = load_iris()
# переводим в датафрейм
df = pd.DataFrame(data = data['data'], columns = data['feature_names'])
# добавляем целевую переменную
df['target'] = data['target']

df.head(10)


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0

In [22]:
df.shape, np.unique(df.target)

((150, 5), array([0, 1, 2]))

In [25]:
# Убирвем данные по setosa, оставляем versicolor=0; virginica=1

df['target'] -= 1 
df = df[df.target != -1]
# переиндексуем
df.reset_index(drop=True, inplace=True)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                6.3               3.3                6.0               2.5   
1                5.8               2.7                5.1               1.9   
2                7.1               3.0                5.9               2.1   
3                6.3               2.9                5.6               1.8   
4                6.5               3.0                5.8               2.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [26]:
# объявим переменные
X = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]
y = df['target']

In [27]:
# добавим столбец с единицами
X.insert(0,'x0', np.ones(X.shape[0]))
 


x0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0  1.0                6.3               3.3                6.0   
1  1.0                5.8               2.7                5.1   
2  1.0                7.1               3.0                5.9   
3  1.0                6.3               2.9                5.6   
4  1.0                6.5               3.0                5.8   

   petal width (cm)  
0               2.5  
1               1.9  
2               2.1  
3               1.8  
4               2.2

In [28]:
# вектор начальных весов (начальное значение - 0)
thetas, n = np.zeros(X.shape[1]), X.shape[0]
thetas, n


(array([0., 0., 0., 0., 0.]), 50)

In [29]:
#  список, в который будем записывать размер ошибки функции потерь

loss_history = []

In [30]:
# сигмоида
def stable_sigmoid(z):
  if z >= 0:
      return 1 / (1 + np.exp(-z))
  else:
      return np.exp(z) / (np.exp(z) + 1)

In [ ]:
# логистическая регрессия
def h(x, thetas):
  z = np.dot(x, thetas)
 
  return np.array([stable_sigmoid(value) for value in z])

In [ ]:
# функция бинарной кросс-энтропии
def objective(y, y_pred):
 
  # рассчитаем функцию потерь для y = 1, добавив 1e-9, чтобы избежать ошибки при log(0)
  y_one_loss = y * np.log(y_pred + 1e-9)
 
  # также рассчитаем функцию потерь для y = 0
  y_zero_loss = (1 - y) * np.log(1 - y_pred + 1e-9)
 
  # сложим и разделим на количество наблюдений
  return -np.mean(y_zero_loss + y_one_loss)


In [ ]:
# Sigmoid function
def sigm(z):
    return 1.0/(1.0+np.exp(-z))

# функция потерь
def logloss(theta, x, y):  
    m = len(y)
    X = np.insert(x, 0, values=1, axis=1)
    h_theta = g(X.dot(theta))
    J = (1.0/m)* (((-y).transpose()).dot(np.log(h_theta)) - (1.0 -y.transpose()).dot(np.log(1.0-h_theta)))
    J = np.float64(J)
    return J

In [ ]:
arr = np.array([3, 1, 9])
arr1 = np.array([2, 6, 4])
arr2 = np.dot(arr, arr1)

arr2

48

----

In [4]:
from sklearn import datasets

# импортируем датасет о вине из модуля datasets
data = datasets.load_wine()
 
# превратим его в датафрейм
df = pd.DataFrame(data.data, columns = data.feature_names)
 
# добавим целевую переменную
df['target'] = data.target
 
# посмотрим на первые три строки
df.head(3)


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0

In [5]:
df.shape, np.unique(df.target)

((178, 14), array([0, 1, 2]))

In [6]:
# применим маску датафрейма и удалим класс 2
df = df[df.target != 2]
 
# посмотрим на результат
df.shape, df.target.unique()

((130, 14), array([0, 1]))

In [7]:
X = df[['alcohol', 'proline']]
y = df['target']

In [9]:
# добавим столбец с единицами
X.insert(0,'x0', np.ones(X.shape[0]))
 
# и посмотрим на результат
X.head()

x0  alcohol  proline
0  1.0    14.23   1065.0
1  1.0    13.20   1050.0
2  1.0    13.16   1185.0
3  1.0    14.37   1480.0
4  1.0    13.24    735.0

In [10]:
# вектор начальных весов (начальное значение - 0)
thetas, n = np.zeros(X.shape[1]), X.shape[0]
thetas, n


(array([0., 0., 0.]), 130)

In [11]:
#  список, в который будем записывать размер ошибки функции потерь

loss_history = []

In [12]:
# сигмоида
def stable_sigmoid(z):
  if z >= 0:
      return 1 / (1 + np.exp(-z))
  else:
      return np.exp(z) / (np.exp(z) + 1)

In [13]:
def h(x, thetas):
  z = np.dot(x, thetas)
 
  return np.array([stable_sigmoid(value) for value in z])

In [14]:
#функцию логистической ошибки
def objective(y, y_pred):
 
  # рассчитаем функцию потерь для y = 1, добавив 1e-9, чтобы избежать ошибки при log(0)
  y_one_loss = y * np.log(y_pred + 1e-9)
 
  # также рассчитаем функцию потерь для y = 0
  y_zero_loss = (1 - y) * np.log(1 - y_pred + 1e-9)
 
  # сложим и разделим на количество наблюдений
  return -np.mean(y_zero_loss + y_one_loss)

In [15]:
def gradient(x, y, y_pred, n):
  return np.dot(x.T, (y_pred - y)) / n

In [16]:
# в цикле из 20000 итераций
for i in range(20000):
  # рассчитаем прогнозное значение с текущими весами
  y_pred = h(X, thetas)
  # посчитаем уровень ошибки при текущем прогнозе
  loss_history.append(objective(y, y_pred))
  # рассчитаем градиент
  grad = gradient(X, y, y_pred, n)
  # используем градиент для улучшения весов модели
  # коэффициент скорости обучения будет равен 0,001
  thetas = thetas - 0.001 * grad

In [17]:
thetas, loss_history[-1]


(array([ 1.16338838, 11.83579745, -0.19826671]), 1.1917145640444533)

In [18]:
# Объявим функцию predict(), которая будет предсказывать к какому классу относится то или иное наблюдение.
def predict(x, thetas):
  # найдем значение линейной функции
  z = np.dot(x, thetas)
  # проведем его через устойчивую сигмоиду
  probs = np.array([stable_sigmoid(value) for value in z])
  # если вероятность больше или равна 0,5 - отнесем наблюдение к классу 1, 
  # в противном случае к классу 0
  # дополнительно выведем значение вероятности
  return np.where(probs >= 0.5, 1, 0), probs

In [19]:
# запишем прогноз класса и вероятность этого прогноза в переменные y_pred и probs
y_pred, probs = predict(X, thetas)
 
# посмотрим на прогноз и вероятность для первого наблюдения
y_pred[0], probs[0]

(0, 8.86276061401868e-19)

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix

# функцию confusion_matrix() мы импортировали в начале ноутбука
# столбцами будут прогнозные значения (Forecast),
# строками - фактические (Actual)
pd.DataFrame(confusion_matrix(y, y_pred),
             columns = ['Forecast 0', 'Forecast 1'],
             index = ['Actual 0', 'Actual 1'])

Forecast 0  Forecast 1
Actual 0          53           6
Actual 1           5          66